feat: update install dependencies workflow

diff --git a/.github/workflows/pr-coverage.yml b/.github/workflows/pr-coverage.yml
--- a/.github/workflows/pr-coverage.yml
+++ b/.github/workflows/pr-coverage.yml
@@ -31,8 +31,26 @@ jobs:
               with:
                   node-version: 20
 
-            - name: Install pnpm
-              run: npm install -g pnpm
+            - name: Check and Install pnpm
+              run: |
+                  if ! command -v pnpm &> /dev/null
+                  then
+                    echo "pnpm not found, installing..."
+                    npm install -g pnpm@9.15.3
+                  else
+                    echo "pnpm is already installed."
+                  fi
+                    echo "checking pnpm version..."
+                  pnpm -v
+
+            - name: Cache pnpm store
+              uses: actions/cache@v3
+              with:
+                  path: ${{ github.workspace }}/.pnpm-store
+                  key: pnpm-store-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
+                  restore-keys: |
+                      pnpm-store-${{ runner.os }}-
+                      pnpm-store-
 
             - name: Install dependencies
               run: pnpm install --store-dir=${{ github.workspace }}/.pnpm-store --node-linker=hoisted --frozen-lockfile
